import type { DevTuningField } from '../devTuningTypes'

const KMH = { unit: 'km/h', factor: 3.6 }

/** Reglages du personnage : deplacement, saut, combat, gabarit. */
export const PLAYER_FIELDS: DevTuningField[] = [
  f({
    id: 'player.WALK_SPEED',
    group: 'movement',
    level: 'simple',
    label: 'Vitesse de marche',
    unit: 'm/s',
    readout: KMH,
    help: 'Vitesse du perso quand il avance normalement.',
    lower: 'Deplacement de promenade, la ville parait immense.',
    higher: 'On traverse Beauvais sans courir.',
    useCase: 'Regler le rythme des deplacements a pied.',
    min: 0,
    max: 20,
    step: 0.1,
  }),
  f({
    id: 'player.RUN_SPEED',
    group: 'movement',
    level: 'simple',
    label: 'Vitesse de course',
    unit: 'm/s',
    readout: KMH,
    help: 'Vitesse en maintenant Maj.',
    lower: 'Courir ne sert presque a rien.',
    higher: 'Le perso court plus vite qu un scooter : tres cartoon.',
    useCase: 'Doser l ecart entre marcher et courir.',
    warning: 'Doit rester au-dessus de la vitesse de marche, sinon courir ralentit.',
    min: 0,
    max: 30,
    step: 0.1,
  }),
  f({
    id: 'player.CROUCH_SPEED',
    group: 'movement',
    level: 'simple',
    label: 'Vitesse accroupi',
    unit: 'm/s',
    readout: KMH,
    help: 'Vitesse en position accroupie.',
    lower: 'Se faufiler devient tres lent.',
    higher: 'Accroupi ne coute presque rien.',
    useCase: 'Equilibrer les passages discrets.',
    min: 0,
    max: 12,
    step: 0.1,
  }),
  f({
    id: 'player.TURN_SPEED',
    group: 'movement',
    level: 'simple',
    label: 'Vivacite de rotation',
    help: 'Rapidite avec laquelle le perso se tourne vers sa direction de marche.',
    lower: 'Le perso pivote lentement, sensation de lourdeur.',
    higher: 'Demi-tours instantanes, un peu robotiques.',
    useCase: 'Ressenti des changements de direction.',
    min: 0,
    max: 30,
    step: 0.1,
  }),
  f({
    id: 'player.JUMP_SPEED',
    group: 'jump',
    level: 'simple',
    label: 'Force du saut',
    unit: 'm/s',
    help: 'Elan vertical au moment du saut.',
    lower: 'Petits sauts, on ne monte sur rien.',
    higher: 'Sauts de super-heros.',
    useCase: 'A regler avec la gravite : les deux font la hauteur de saut.',
    warning: 'Change la hauteur ET la portee des sauts.',
    min: 0,
    max: 20,
    step: 0.1,
  }),
  f({
    id: 'player.GRAVITY',
    group: 'jump',
    level: 'simple',
    label: 'Gravite du perso',
    unit: 'm/s2',
    help: 'Poids ressenti pendant un saut. 9,81 = gravite reelle.',
    lower: 'Sauts flottants facon lune.',
    higher: 'Le perso retombe sec, sauts courts et nerveux.',
    useCase: 'Rendre les sauts plus punchy sans changer leur hauteur (monter les deux).',
    min: 0,
    max: 50,
    step: 0.1,
  }),
  f({
    id: 'player.COMBO_DURATIONS.0',
    group: 'combat',
    level: 'simple',
    label: 'Duree du 1er coup',
    unit: 's',
    help: 'Temps que dure la premiere animation de poing.',
    lower: 'Coup rapide et sec.',
    higher: 'Coup appuye, plus lourd.',
    useCase: 'Rythme de l enchainement a mains nues.',
    warning: 'Trop court = animation saccadee (les FBX durent 0,70 s a l origine).',
    min: 0.1,
    max: 2,
    step: 0.01,
  }),
  f({
    id: 'player.COMBO_DURATIONS.1',
    group: 'combat',
    level: 'simple',
    label: 'Duree du 2e coup',
    unit: 's',
    help: 'Temps que dure la deuxieme animation de poing.',
    lower: 'Enchainement plus nerveux.',
    higher: 'Enchainement plus lourd.',
    useCase: 'Rythme de l enchainement a mains nues.',
    min: 0.1,
    max: 2,
    step: 0.01,
  }),
  f({
    id: 'player.COMBO_DURATIONS.2',
    group: 'combat',
    level: 'simple',
    label: 'Duree du 3e coup',
    unit: 's',
    help: 'Temps que dure le troisieme coup, volontairement plus lourd.',
    lower: 'Le coup final perd son impact.',
    higher: 'Grosse frappe finale, mais on reste expose.',
    useCase: 'Appuyer la fin de l enchainement.',
    min: 0.1,
    max: 2.5,
    step: 0.01,
  }),
  f({
    id: 'player.COMBO_WINDOW',
    group: 'combat',
    level: 'simple',
    label: 'Fenetre d enchainement',
    unit: 's',
    help: 'Delai apres un coup pendant lequel un nouveau clic enchaine au lieu de repartir du coup 1.',
    lower: 'Il faut cliquer tres juste pour enchainer.',
    higher: 'L enchainement pardonne tout.',
    useCase: 'Rendre le combat plus ou moins exigeant.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
  f({
    id: 'player.WEAPON_ATTACK_DURATION',
    group: 'combat',
    level: 'simple',
    label: 'Duree d attaque avec arme',
    unit: 's',
    help: 'Temps d une attaque quand une arme est equipee.',
    lower: 'Attaques rapides, arme legere.',
    higher: 'Attaques lentes, arme lourde.',
    useCase: 'Differencier le combat a mains nues du combat arme.',
    min: 0.1,
    max: 3,
    step: 0.01,
  }),
  f({
    id: 'player.HURT_DURATION',
    group: 'combat',
    level: 'simple',
    label: 'Duree d etourdissement',
    unit: 's',
    help: 'Temps pendant lequel le perso encaisse et ne peut rien faire.',
    lower: 'On reprend la main tout de suite.',
    higher: 'Se faire toucher devient tres punitif.',
    useCase: 'Difficulte des bagarres.',
    min: 0,
    max: 4,
    step: 0.01,
  }),
  f({
    id: 'player.INTERACT_DURATION',
    group: 'combat',
    level: 'advanced',
    label: 'Duree du geste d interaction',
    unit: 's',
    help: 'Temps de l animation quand on appuie sur E.',
    lower: 'Interactions instantanees.',
    higher: 'Geste visible mais on attend.',
    useCase: 'Confort des interactions repetees.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
  f({
    id: 'player.BODY_HEIGHT',
    group: 'body',
    level: 'advanced',
    label: 'Hauteur du corps',
    unit: 'm',
    help: 'Hauteur du centre du corps au-dessus du sol.',
    lower: 'Le perso s enfonce dans le sol.',
    higher: 'Il flotte au-dessus.',
    useCase: 'Recaler le perso sur un nouveau modele.',
    min: 0.2,
    max: 3,
    step: 0.01,
  }),
  f({
    id: 'player.BODY_RADIUS',
    group: 'body',
    level: 'advanced',
    label: 'Rayon de collision',
    unit: 'm',
    help: 'Rayon du cylindre qui glisse le long des murs.',
    lower: 'Le perso passe dans des interstices trop fins.',
    higher: 'Il reste coince dans les portes.',
    useCase: 'Si le perso accroche partout ou traverse les murs.',
    min: 0.1,
    max: 1.5,
    step: 0.01,
  }),
]

function f(entry: Omit<DevTuningField, 'section' | 'kind'>): DevTuningField {
  return { ...entry, section: 'player', kind: 'number' }
}
