import type { DevTuningField, VehicleKind } from '../devTuningTypes'

/** Lecture secondaire : m/s -> km/h. */
const KMH = { unit: 'km/h', factor: 3.6 }
/** Lecture secondaire : radians -> degres. */
const DEG = { unit: 'deg', factor: 180 / Math.PI }

/**
 * Les reglages d'un vehicule, ranges par categorie comprehensible.
 *
 * Le `forceStep` change entre voiture et scooter parce qu'une force de 12 000 N
 * ne se regle pas au meme grain qu'une force de 900 N.
 */
export function vehicleFields(kind: VehicleKind): DevTuningField[] {
  const forceStep = kind === 'car' ? 50 : 5
  const f = (entry: Omit<DevTuningField, 'section' | 'kind' | 'id'> & { key: string }): DevTuningField => ({
    ...entry,
    id: `vehicles.${kind}.${entry.key}`,
    section: kind,
    kind: 'number',
  })

  return [
    // --- Comportement general ---------------------------------------------
    f({
      key: 'MASS',
      group: 'general',
      level: 'simple',
      label: 'Masse totale',
      unit: 'kg',
      help: 'Poids du vehicule avec son conducteur. Il pese sur TOUT : acceleration, freinage, virages, chocs.',
      lower: 'Plus vif, tourne plus court, mais se fait pousser au moindre choc.',
      higher: 'Plus lourd et plus stable, mais mou a l acceleration et long a arreter.',
      useCase: 'Pour rendre le vehicule plus « pataud » ou plus « leger » sans toucher au moteur.',
      warning: 'Si tu montes la masse, il faut souvent monter aussi le couple moteur et le freinage.',
      min: 20,
      max: 3000,
      step: 5,
    }),
    f({
      key: 'MOUNT_RANGE',
      group: 'general',
      level: 'simple',
      label: 'Distance pour monter',
      unit: 'm',
      help: 'A quelle distance le joueur peut monter dans le vehicule.',
      lower: 'Il faut se coller au vehicule.',
      higher: 'On monte de loin, pratique mais moins credible.',
      useCase: 'Si monter dans la voiture est penible a viser.',
      min: 0.5,
      max: 8,
      step: 0.1,
    }),
    f({
      key: 'SEAT_HEIGHT',
      group: 'general',
      level: 'advanced',
      label: 'Hauteur d assise',
      unit: 'm',
      help: 'Hauteur du personnage une fois assis, purement visuelle.',
      lower: 'Le perso s enfonce dans le siege.',
      higher: 'Le perso flotte au-dessus.',
      useCase: 'Recaler le perso sur un nouveau modele 3D.',
      min: 0.2,
      max: 2.5,
      step: 0.01,
    }),
    f({
      key: 'COLLISION_HALF_LENGTH',
      group: 'general',
      level: 'advanced',
      label: 'Demi-longueur de collision',
      unit: 'm',
      help: 'Moitie de la longueur de la boite qui cogne le decor.',
      lower: 'Le vehicule passe dans des trous ou il ne devrait pas.',
      higher: 'Il accroche des murs avant de les toucher visuellement.',
      useCase: 'Uniquement quand le modele 3D change.',
      warning: 'Valeur calee sur le modele FBX : la bouger au hasard casse le contact avec le decor.',
      min: 0.2,
      max: 5,
      step: 0.01,
    }),
    f({
      key: 'COLLISION_HALF_WIDTH',
      group: 'general',
      level: 'advanced',
      label: 'Demi-largeur de collision',
      unit: 'm',
      help: 'Moitie de la largeur de la boite qui cogne le decor.',
      lower: 'Le vehicule se faufile trop facilement.',
      higher: 'Il reste coince dans les rues etroites.',
      useCase: 'Uniquement quand le modele 3D change.',
      warning: 'Valeur calee sur le modele FBX.',
      min: 0.1,
      max: 2,
      step: 0.01,
    }),

    // --- Moteur ------------------------------------------------------------
    f({
      key: 'ENGINE.PEAK_TORQUE',
      group: 'engine',
      level: 'simple',
      label: 'Puissance du moteur',
      unit: 'N.m',
      help: 'Force maximale que le moteur envoie aux roues. C est le reglage n°1 des reprises.',
      lower: 'Demarrages mous, cotes penibles.',
      higher: 'Ca arrache, quitte a patiner et a partir en travers.',
      useCase: 'Quand le vehicule « ne pousse pas » assez.',
      warning: 'Ne change presque pas la vitesse maximale : celle-ci vient surtout de la trainee de l air.',
      min: 0,
      max: 600,
      step: 1,
    }),
    f({
      key: 'ENGINE_BRAKE',
      group: 'engine',
      level: 'simple',
      label: 'Frein moteur',
      unit: 'N',
      help: 'Ralentissement automatique quand on lache l accelerateur.',
      lower: 'Le vehicule roule en roue libre tres longtemps.',
      higher: 'Il ralentit fort des qu on leve le pied, comme sur un gros rapport.',
      useCase: 'Pour doser la conduite « une seule pedale » en ville.',
      min: 0,
      max: 3000,
      step: forceStep,
    }),
    f({
      key: 'ENGINE.PEAK_RPM',
      group: 'engine',
      level: 'advanced',
      label: 'Regime de puissance max',
      unit: 'tr/min',
      help: 'Regime auquel le moteur donne le maximum.',
      lower: 'Moteur coupleux en bas, style diesel.',
      higher: 'Il faut monter dans les tours, style moteur sportif.',
      useCase: 'Pour donner un caractere de moteur.',
      min: 500,
      max: 10000,
      step: 50,
    }),
    f({
      key: 'ENGINE.IDLE_RPM',
      group: 'engine',
      level: 'advanced',
      label: 'Ralenti',
      unit: 'tr/min',
      help: 'Regime moteur a l arret.',
      lower: 'Moteur qui broute.',
      higher: 'Moteur qui tourne haut a l arret.',
      useCase: 'Cosmetique (aiguille et son moteur).',
      min: 200,
      max: 3000,
      step: 50,
    }),
    f({
      key: 'ENGINE.MAX_RPM',
      group: 'engine',
      level: 'advanced',
      label: 'Zone rouge',
      unit: 'tr/min',
      help: 'Regime maximal avant coupure.',
      lower: 'Le moteur bute vite, il faut passer les rapports tot.',
      higher: 'On peut tirer les rapports plus longtemps.',
      useCase: 'A ajuster avec le regime de passage de rapport.',
      min: 1000,
      max: 12000,
      step: 50,
    }),
    f({
      key: 'ENGINE.EFFICIENCY',
      group: 'engine',
      level: 'advanced',
      label: 'Rendement transmission',
      help: 'Part de la force moteur qui arrive vraiment aux roues.',
      lower: 'Transmission qui mange la puissance.',
      higher: 'Presque rien ne se perd (peu realiste au-dessus de 1).',
      useCase: 'Reglage fin de la poussee sans toucher au couple.',
      min: 0.1,
      max: 1.2,
      step: 0.01,
    }),
    f({
      key: 'ENGINE.FINAL_DRIVE',
      group: 'engine',
      level: 'advanced',
      label: 'Pont final',
      help: 'Demultiplication finale, commune a tous les rapports.',
      lower: 'Rapports longs : vitesse de pointe, reprises molles.',
      higher: 'Rapports courts : ca pousse fort mais ca tape vite la zone rouge.',
      useCase: 'Quand toute la boite est trop courte ou trop longue.',
      min: 0.1,
      max: 10,
      step: 0.01,
    }),
    f({
      key: 'ENGINE.SHIFT_UP_RPM',
      group: 'engine',
      level: 'advanced',
      label: 'Passage rapport superieur',
      unit: 'tr/min',
      help: 'Regime auquel la boite automatique monte un rapport.',
      lower: 'Conduite economique, moteur qui ne chante jamais.',
      higher: 'On tire les rapports jusqu en haut.',
      useCase: 'Pour caler la boite sur la zone rouge.',
      warning: 'Doit rester en dessous de la zone rouge.',
      min: 0,
      max: 12000,
      step: 50,
    }),
    f({
      key: 'ENGINE.SHIFT_DOWN_RPM',
      group: 'engine',
      level: 'advanced',
      label: 'Retrogradage',
      unit: 'tr/min',
      help: 'Regime en dessous duquel la boite descend un rapport.',
      lower: 'La boite s accroche aux grands rapports.',
      higher: 'Elle retrograde vite, moteur toujours dans les tours.',
      useCase: 'Si le vehicule cale en sortie de virage.',
      min: 0,
      max: 8000,
      step: 50,
    }),
    f({
      key: 'ENGINE.SHIFT_TIME',
      group: 'engine',
      level: 'advanced',
      label: 'Temps de passage',
      unit: 's',
      help: 'Trou de couple pendant un changement de rapport. C est lui qui fait SENTIR la boite.',
      lower: 'Passages instantanes, tres arcade.',
      higher: 'Grosse coupure a chaque rapport, on perd de la vitesse.',
      useCase: 'Pour rendre les accelerations plus « mecaniques ».',
      min: 0,
      max: 1,
      step: 0.01,
    }),
    f({
      key: 'ENGINE.CVT_TARGET_RPM',
      group: 'engine',
      level: 'advanced',
      label: 'Variateur : regime tenu',
      unit: 'tr/min',
      help: 'Regime que le variateur maintient sous les gaz (scooter uniquement).',
      lower: 'Scooter qui ronronne.',
      higher: 'Scooter qui hurle en permanence.',
      useCase: 'Reglage du son et de la poussee du scooter.',
      warning: 'Sans effet sur un vehicule a boite de vitesses.',
      min: 0,
      max: 10000,
      step: 50,
    }),
    f({
      key: 'ENGINE.CVT_RATIO_MIN',
      group: 'engine',
      level: 'advanced',
      label: 'Variateur : rapport le plus long',
      help: 'Rapport atteint a haute vitesse. C est lui qui borne la pointe du scooter.',
      lower: 'Vitesse de pointe plus elevee.',
      higher: 'Vitesse de pointe bridee.',
      useCase: 'Debrider ou brider un scooter.',
      min: 0,
      max: 40,
      step: 0.05,
    }),
    f({
      key: 'ENGINE.CVT_RATIO_MAX',
      group: 'engine',
      level: 'advanced',
      label: 'Variateur : rapport le plus court',
      help: 'Rapport au demarrage : la poussee des premiers metres.',
      lower: 'Demarrages mous.',
      higher: 'Ca part fort au feu vert.',
      useCase: 'Regler le punch a l arret.',
      min: 0,
      max: 50,
      step: 0.05,
    }),

    // --- Vitesse maximale ---------------------------------------------------
    f({
      key: 'DRAG',
      group: 'topspeed',
      level: 'simple',
      label: 'Resistance de l air',
      help: 'Freinage aerodynamique qui augmente avec la vitesse. C EST LUI qui fixe la vitesse de pointe.',
      lower: 'Vitesse de pointe plus haute, et beaucoup plus longue a atteindre.',
      higher: 'Le vehicule plafonne tot, comme un vehicule pas profile.',
      useCase: 'Le bon reglage pour rendre un vehicule plus rapide, plutot que de monter le moteur.',
      warning: 'La vitesse maximale n est PAS reglee directement : elle sort de l equilibre poussee / trainee.',
      min: 0,
      max: 2,
      step: 0.001,
    }),
    f({
      key: 'MAX_SPEED',
      group: 'topspeed',
      level: 'simple',
      label: 'Vitesse maximale de securite',
      unit: 'm/s',
      readout: KMH,
      help: 'Plafond dur de vitesse. Sert de garde-fou (descentes, bugs), pas de reglage de pointe.',
      lower: 'Le vehicule bute artificiellement sur ce plafond.',
      higher: 'Le plafond ne se voit jamais, la trainee limite avant.',
      useCase: 'Empecher une descente de transformer la voiture en fusee.',
      warning: 'Pour changer la vraie vitesse de pointe, regle la resistance de l air.',
      min: 1,
      max: 100,
      step: 0.5,
    }),
    f({
      key: 'ROLL_RESIST',
      group: 'topspeed',
      level: 'advanced',
      label: 'Resistance au roulement',
      help: 'Frottement des pneus, present meme a basse vitesse.',
      lower: 'Le vehicule roule tres longtemps en roue libre.',
      higher: 'Il s arrete de lui-meme, comme sur du sable.',
      useCase: 'Pour rendre les manoeuvres lentes plus ou moins collantes.',
      min: 0,
      max: 0.1,
      step: 0.001,
    }),

    // --- Freinage ----------------------------------------------------------
    f({
      key: 'BRAKE_FORCE',
      group: 'brakes',
      level: 'simple',
      label: 'Puissance de freinage',
      unit: 'N',
      help: 'Force des freins principaux.',
      lower: 'Distances d arret longues, il faut anticiper.',
      higher: 'Arret quasi instantane, tres arcade.',
      useCase: 'Le premier reglage a toucher si le vehicule est dangereux en ville.',
      warning: 'A comparer avec la masse : un vehicule lourd a besoin de plus de frein.',
      min: 0,
      max: 25000,
      step: forceStep,
    }),
    f({
      key: 'REVERSE_SPEED',
      group: 'brakes',
      level: 'simple',
      label: 'Vitesse en marche arriere',
      unit: 'm/s',
      readout: KMH,
      help: 'Vitesse maximale en reculant.',
      lower: 'Manoeuvres lentes et prudentes.',
      higher: 'On peut faire des demi-tours a l arrache.',
      useCase: 'Confort de manoeuvre dans les rues etroites.',
      min: 0,
      max: 20,
      step: 0.1,
    }),
    f({
      key: 'REVERSE_FORCE',
      group: 'brakes',
      level: 'advanced',
      label: 'Poussee en marche arriere',
      unit: 'N',
      help: 'Force disponible pour reculer.',
      lower: 'On peine a reculer dans une cote.',
      higher: 'On recule presque aussi vite qu on avance.',
      useCase: 'Si sortir d une impasse est penible.',
      min: 0,
      max: 10000,
      step: forceStep,
    }),
    f({
      key: 'LIMITER_MIN_SPEED',
      group: 'brakes',
      level: 'advanced',
      label: 'Limiteur : vitesse minimale',
      unit: 'm/s',
      readout: KMH,
      help: 'En dessous de cette vitesse, enclencher le limiteur ne fait rien.',
      lower: 'On peut limiter meme au pas.',
      higher: 'Le limiteur ne sert qu a vitesse de croisiere.',
      useCase: 'Eviter un limiteur enclenche par erreur a l arret.',
      min: 0,
      max: 30,
      step: 0.5,
    }),
    f({
      key: 'LIMITER_FADE_SPEED',
      group: 'brakes',
      level: 'advanced',
      label: 'Limiteur : douceur',
      unit: 'm/s',
      help: 'Marge sur laquelle les gaz se referment en approchant de la vitesse limitee.',
      lower: 'Coupure seche, le vehicule fait un a-coup.',
      higher: 'Arrivee tres douce sur la vitesse cible.',
      useCase: 'Si le limiteur provoque des secousses.',
      min: 0,
      max: 10,
      step: 0.1,
    }),

    // --- Direction ---------------------------------------------------------
    f({
      key: 'MAX_STEER_ANGLE',
      group: 'steering',
      level: 'simple',
      label: 'Braquage maximal',
      unit: 'rad',
      readout: DEG,
      help: 'Angle maximal des roues avant. Determine le rayon de braquage.',
      lower: 'Grands virages, demi-tours impossibles.',
      higher: 'Tourne tres court, mais devient nerveux et instable a haute vitesse.',
      useCase: 'Si le vehicule ne passe pas dans les rues de Beauvais.',
      min: 0,
      max: 1.3,
      step: 0.01,
    }),
    f({
      key: 'STEER_RESPONSE',
      group: 'steering',
      level: 'simple',
      label: 'Vivacite de la direction',
      help: 'Rapidite avec laquelle les roues rejoignent l angle demande.',
      lower: 'Direction lente et molle, sensation de camion.',
      higher: 'Reponse immediate, tres arcade et un peu nerveuse.',
      useCase: 'Le reglage de « ressenti » de la direction au clavier.',
      min: 0,
      max: 20,
      step: 0.1,
    }),
    f({
      key: 'VISUAL_STEER_MAX',
      group: 'steering',
      level: 'advanced',
      label: 'Braquage visible des roues',
      unit: 'rad',
      readout: DEG,
      help: 'Angle maximal AFFICHE pour les roues. Purement cosmetique.',
      lower: 'Roues qui bougent a peine a l ecran.',
      higher: 'Roues tres tournees, parfois en dehors des passages de roue.',
      useCase: 'Rendre le braquage lisible sans changer la tenue de route.',
      warning: 'N a aucun effet sur la physique.',
      min: 0,
      max: 0.8,
      step: 0.01,
    }),

    // --- Adherence ---------------------------------------------------------
    f({
      key: 'GRIP',
      group: 'grip',
      level: 'simple',
      label: 'Accroche laterale des pneus',
      help: 'Vitesse a laquelle le vehicule arrete de glisser sur le cote.',
      lower: 'Ca part en glisse au moindre appui : savonnette.',
      higher: 'Le vehicule est sur des rails.',
      useCase: 'Le reglage principal entre conduite realiste et conduite arcade.',
      warning: 'Travaille avec l adherence maximale en virage : baisser les deux rend le vehicule incontrolable.',
      min: 0,
      max: 25,
      step: 0.1,
    }),
    f({
      key: 'MAX_LATERAL_G',
      group: 'grip',
      level: 'simple',
      label: 'Adherence maximale en virage',
      unit: 'g',
      help: 'Acceleration laterale que les pneus tiennent avant de sous-virer. Une voiture de route tient ~0,95 g.',
      lower: 'Le vehicule part tout droit des qu on tourne vite.',
      higher: 'Virages a plat irrealistes, mais tres joueurs.',
      useCase: 'Calibrer le realisme de la tenue de route.',
      min: 0.1,
      max: 2,
      step: 0.01,
    }),
    f({
      key: 'STEER_ASSIST_G',
      group: 'grip',
      level: 'simple',
      label: 'Aide au virage (arcade)',
      unit: 'g',
      help: 'Bonus d adherence ajoute a haute vitesse pour que le vehicule reste pilotable au clavier.',
      lower: 'Comportement plus realiste et plus exigeant.',
      higher: 'Le vehicule tourne comme sur un jeu arcade, meme lance.',
      useCase: 'Le curseur « realiste / arcade » le plus direct.',
      min: 0,
      max: 1.5,
      step: 0.01,
    }),
    f({
      key: 'SURFACE_GRIP_OFFROAD',
      group: 'grip',
      level: 'simple',
      label: 'Adherence hors bitume',
      help: 'Part d adherence conservee sur terre, herbe ou trottoir.',
      lower: 'La terre devient une patinoire.',
      higher: 'On roule hors route comme sur route.',
      useCase: 'Rendre les raccourcis par les champs plus ou moins risques.',
      min: 0,
      max: 1,
      step: 0.01,
    }),
    f({
      key: 'SURFACE_GRIP_ROAD',
      group: 'grip',
      level: 'advanced',
      label: 'Adherence sur bitume',
      help: 'Adherence de reference sur la route. 1 = normale.',
      lower: 'Route mouillee en permanence.',
      higher: 'Adherence de piste, au-dela du realiste.',
      useCase: 'Simuler la pluie ou le verglas.',
      min: 0,
      max: 1.5,
      step: 0.01,
    }),

    // --- Drift -------------------------------------------------------------
    f({
      key: 'HANDBRAKE_REAR_GRIP',
      group: 'drift',
      level: 'simple',
      label: 'Adherence des roues arriere (frein a main)',
      help: 'Adherence qui reste a l arriere quand le frein a main est tire.',
      lower: 'L arriere decroche tout de suite : glissades faciles et longues.',
      higher: 'L arriere reste colle : presque pas de drift.',
      useCase: 'LE reglage du drift. Baisse-le pour glisser plus facilement.',
      min: 0,
      max: 1,
      step: 0.01,
    }),
    f({
      key: 'HANDBRAKE_FORCE',
      group: 'drift',
      level: 'simple',
      label: 'Force du frein a main',
      unit: 'N',
      help: 'Freinage applique sur l arriere quand on tire le frein a main.',
      lower: 'Le frein a main ralentit a peine.',
      higher: 'Il stoppe presque le vehicule, ce qui casse les drifts.',
      useCase: 'Doser entre « glisser » et « s arreter ».',
      warning: 'Toujours plus faible que le frein principal, sinon le drift devient un arret.',
      min: 0,
      max: 15000,
      step: forceStep,
    }),
    f({
      key: 'DRIFT_STEER_AUTHORITY',
      group: 'drift',
      level: 'simple',
      label: 'Controle pendant la glisse',
      help: 'Part de direction conservee quand le vehicule est en travers.',
      lower: 'Une fois parti en glisse, on ne rattrape rien : spectaculaire, punitif.',
      higher: 'On dirige presque normalement en drift : tres arcade.',
      useCase: 'Rendre les drifts rattrapables ou non.',
      min: 0,
      max: 1,
      step: 0.01,
    }),

    // --- Suspension --------------------------------------------------------
    f({
      key: 'SUSPENSION_TRAVEL',
      group: 'suspension',
      level: 'simple',
      label: 'Debattement de suspension',
      unit: 'm',
      help: 'Hauteur de bosse que les roues absorbent avant que la caisse decolle.',
      lower: 'Chassis rigide : la moindre bosse fait sauter le vehicule.',
      higher: 'Suspension molle qui gomme les trottoirs, mais qui tangue.',
      useCase: 'Confort de conduite sur les trottoirs et les paves de Beauvais.',
      min: 0.05,
      max: 1.5,
      step: 0.01,
    }),
    f({
      key: 'LANDING_BOUNCE',
      group: 'suspension',
      level: 'simple',
      label: 'Rebond a l atterrissage',
      help: 'Part de vitesse verticale conservee en retombant.',
      lower: 'Atterrissages secs, la suspension avale tout.',
      higher: 'Le vehicule rebondit comme un ballon.',
      useCase: 'Regler le ressenti apres un tremplin.',
      min: 0,
      max: 1,
      step: 0.01,
    }),
    f({
      key: 'WHEEL_RADIUS',
      group: 'suspension',
      level: 'advanced',
      label: 'Rayon des roues',
      unit: 'm',
      help: 'Taille des roues. Influence la hauteur de caisse et la vitesse pour un regime donne.',
      lower: 'Vehicule plus bas, plus court en developpement.',
      higher: 'Vehicule perche, plus long en developpement.',
      useCase: 'Uniquement quand le modele 3D change.',
      warning: 'Valeur calee sur le modele 3D.',
      min: 0.1,
      max: 1,
      step: 0.01,
    }),
    f({
      key: 'WHEELBASE',
      group: 'suspension',
      level: 'advanced',
      label: 'Empattement',
      unit: 'm',
      help: 'Distance entre essieu avant et essieu arriere.',
      lower: 'Vehicule court : pivote vite, plus nerveux.',
      higher: 'Vehicule long : stable en ligne droite, lourd en virage.',
      useCase: 'Uniquement quand le modele 3D change.',
      warning: 'Valeur calee sur le modele 3D.',
      min: 0.5,
      max: 5,
      step: 0.01,
    }),

    // --- Controle aerien ---------------------------------------------------
    f({
      key: 'AIR_GRAVITY',
      group: 'air',
      level: 'simple',
      label: 'Gravite en vol',
      unit: 'm/s2',
      help: 'Poids ressenti pendant un saut. 9,81 = gravite reelle.',
      lower: 'Sauts longs et flottants, style cartoon.',
      higher: 'Le vehicule retombe comme une pierre.',
      useCase: 'Donner de l ampleur ou du poids aux tremplins.',
      min: 0,
      max: 30,
      step: 0.1,
    }),
    f({
      key: 'AIR_PITCH_CONTROL',
      group: 'air',
      level: 'simple',
      label: 'Controle du nez en l air',
      help: 'Capacite a lever ou piquer du nez en vol avec avant / arriere.',
      lower: 'On subit la trajectoire.',
      higher: 'On fait des saltos a volonte.',
      useCase: 'Preparer l atterrissage a plat apres un tremplin.',
      min: 0,
      max: 8,
      step: 0.05,
    }),
    f({
      key: 'AIR_ROLL_CONTROL',
      group: 'air',
      level: 'simple',
      label: 'Controle du tonneau en l air',
      help: 'Capacite a rouler sur le cote en vol avec gauche / droite.',
      lower: 'Le vehicule reste a plat quoi qu il arrive.',
      higher: 'Tonneaux faciles, style jeu de cascades.',
      useCase: 'Autoriser ou non les figures.',
      min: 0,
      max: 10,
      step: 0.05,
    }),
    f({
      key: 'AIR_LEVEL_ASSIST',
      group: 'air',
      level: 'simple',
      label: 'Remise a plat automatique',
      help: 'Sans consigne du joueur, le vehicule revient doucement a l horizontale.',
      lower: 'Aucune aide : on retombe comme on est parti.',
      higher: 'Le vehicule se remet a plat tout seul, atterrissages pardonnants.',
      useCase: 'Rendre les sauts moins punitifs.',
      min: 0,
      max: 6,
      step: 0.05,
    }),
    f({
      key: 'FLIP_RECOVERY_HOLD',
      group: 'air',
      level: 'simple',
      label: 'Temps pour se remettre sur ses roues',
      unit: 's',
      help: 'Duree pendant laquelle il faut maintenir le frein a main, sur le toit, pour se redresser.',
      lower: 'Retournement quasi instantane.',
      higher: 'Il faut vraiment insister, on reste bloque plus longtemps.',
      useCase: 'Eviter de rester coince sur le toit.',
      min: 0,
      max: 5,
      step: 0.05,
    }),
    f({
      key: 'AIR_ROTATION_DAMP',
      group: 'air',
      level: 'advanced',
      label: 'Amortissement des rotations',
      help: 'Vitesse a laquelle une rotation aerienne s essouffle toute seule.',
      lower: 'Le vehicule continue de tourner longtemps.',
      higher: 'Les rotations s arretent des qu on relache.',
      useCase: 'Rendre les figures plus ou moins controlables.',
      min: 0,
      max: 2,
      step: 0.01,
    }),
    f({
      key: 'AIR_PITCH_TORQUE',
      group: 'air',
      level: 'advanced',
      label: 'Couple de tangage',
      help: 'Force brute de rotation avant / arriere en l air.',
      lower: 'Rotation lente a s enclencher.',
      higher: 'Le nez bascule instantanement.',
      useCase: 'Reglage fin, a coupler avec le plafond de rotation.',
      min: 0,
      max: 12,
      step: 0.05,
    }),
    f({
      key: 'AIR_ROLL_TORQUE',
      group: 'air',
      level: 'advanced',
      label: 'Couple de roulis',
      help: 'Force brute de rotation laterale en l air.',
      lower: 'Tonneaux lents.',
      higher: 'Tonneaux immediats.',
      useCase: 'Reglage fin, a coupler avec le plafond de rotation.',
      min: 0,
      max: 12,
      step: 0.05,
    }),
    f({
      key: 'AIR_MAX_RATE',
      group: 'air',
      level: 'advanced',
      label: 'Vitesse de rotation maximale',
      unit: 'rad/s',
      help: 'Plafond de rotation en l air, toutes commandes confondues.',
      lower: 'Figures lentes et lisibles.',
      higher: 'Le vehicule peut devenir une toupie.',
      useCase: 'Garder les figures lisibles a l ecran.',
      min: 0,
      max: 10,
      step: 0.05,
    }),
    f({
      key: 'TAKEOFF_MIN_SPEED',
      group: 'air',
      level: 'advanced',
      label: 'Vitesse minimale pour decoller',
      unit: 'm/s',
      readout: KMH,
      help: 'En dessous, le vehicule reste colle au sol au lieu de sauter.',
      lower: 'Le vehicule decolle au moindre trottoir.',
      higher: 'Il faut vraiment lancer le vehicule pour sauter.',
      useCase: 'Eviter les micro-sauts parasites en ville.',
      min: 0,
      max: 40,
      step: 0.5,
    }),
    f({
      key: 'TAKEOFF_MIN_VELOCITY',
      group: 'air',
      level: 'advanced',
      label: 'Impulsion minimale de decollage',
      unit: 'm/s',
      help: 'Vitesse verticale minimale que le sol doit transmettre pour lancer un saut.',
      lower: 'Le moindre relief envoie le vehicule en l air.',
      higher: 'Seules les vraies rampes font decoller.',
      useCase: 'Nettoyer les sauts involontaires.',
      min: 0,
      max: 5,
      step: 0.01,
    }),
    f({
      key: 'TAKEOFF_MIN_PITCH',
      group: 'air',
      level: 'advanced',
      label: 'Angle minimal de tremplin',
      unit: 'rad',
      readout: DEG,
      help: 'Inclinaison du nez necessaire pour decoller quand le sol se derobe.',
      lower: 'Le vehicule s envole meme a plat.',
      higher: 'Il faut une vraie rampe inclinee.',
      useCase: 'Eviter les envols en haut d une cote.',
      min: 0,
      max: 0.4,
      step: 0.01,
    }),
    f({
      key: 'TAKEOFF_ROTATION_IMPULSE',
      group: 'air',
      level: 'advanced',
      label: 'Rotation donnee par le tremplin',
      help: 'Rotation transmise par l inclinaison du sol au moment du decollage.',
      lower: 'Le vehicule part a plat.',
      higher: 'Les rampes envoient le vehicule en rotation.',
      useCase: 'Rendre les tremplins spectaculaires.',
      min: 0,
      max: 10,
      step: 0.05,
    }),

    // --- Chocs -------------------------------------------------------------
    f({
      key: 'SCRAPE_FRICTION',
      group: 'impact',
      level: 'simple',
      label: 'Frottement contre les murs',
      help: 'Vitesse perdue par seconde quand le vehicule rase un obstacle.',
      lower: 'On glisse le long des facades sans ralentir.',
      higher: 'Le moindre frottement casse l elan.',
      useCase: 'Punir ou pardonner la conduite dans les rues etroites.',
      min: 0,
      max: 6,
      step: 0.01,
    }),
    f({
      key: 'IMPACT_RESTITUTION',
      group: 'impact',
      level: 'simple',
      label: 'Rebond sur choc',
      help: 'Part de vitesse renvoyee quand le vehicule tape quelque chose.',
      lower: 'Le vehicule s ecrase sur l obstacle et s arrete.',
      higher: 'Il rebondit comme une bille de flipper.',
      useCase: 'Ton cartoon des collisions.',
      min: 0,
      max: 1,
      step: 0.01,
    }),
    f({
      key: 'IMPACT_SPIN',
      group: 'impact',
      level: 'advanced',
      label: 'Rotation sur choc decentre',
      help: 'Rotation ajoutee quand le choc n est pas pris de face.',
      lower: 'Les chocs ne font jamais tourner la caisse.',
      higher: 'Un coup d aile part en tete-a-queue.',
      useCase: 'Rendre les accrochages plus vivants.',
      min: 0,
      max: 0.5,
      step: 0.005,
    }),
    f({
      key: 'SPIN_DAMP',
      group: 'impact',
      level: 'advanced',
      label: 'Amortissement de la rotation',
      help: 'Vitesse a laquelle la rotation d un choc disparait.',
      lower: 'Le vehicule tournoie longtemps.',
      higher: 'La rotation se calme aussitot.',
      useCase: 'A regler avec la rotation sur choc decentre.',
      min: 0,
      max: 12,
      step: 0.1,
    }),
  ]
}
