import type { DevSectionId, DevTuningField } from '../devTuningTypes'

const DEG = { unit: 'deg', factor: 180 / Math.PI }

/** Camera, inventaire et ciel : tout ce qui n est ni le perso ni un vehicule. */
export const WORLD_FIELDS: DevTuningField[] = [
  // --- Camera -------------------------------------------------------------
  f('camera', {
    id: 'camera.SENSITIVITY',
    group: 'aim',
    level: 'simple',
    label: 'Sensibilite de la souris',
    help: 'Rotation de la camera pour un pixel de souris.',
    lower: 'Visee precise mais il faut beaucoup bouger la main.',
    higher: 'Camera tres reactive, difficile a viser fin.',
    useCase: 'Confort personnel, a regler une fois pour toutes.',
    min: 0.0005,
    max: 0.01,
    step: 0.0001,
  }),
  f('camera', {
    id: 'camera.INVERT_Y',
    group: 'aim',
    level: 'simple',
    label: 'Inverser l axe vertical',
    help: 'Sens de la camera quand on pousse la souris vers le haut. 0 = normal, 1 = inverse.',
    lower: '0 : pousser la souris vers le haut regarde vers le haut.',
    higher: '1 : pousser la souris vers le haut regarde vers le bas (facon pilotage).',
    useCase: 'Preference personnelle.',
    min: 0,
    max: 1,
    step: 1,
  }),
  f('camera', {
    id: 'camera.PITCH_MIN',
    group: 'aim',
    level: 'advanced',
    label: 'Angle bas maximal',
    unit: 'rad',
    readout: DEG,
    help: 'Jusqu ou la camera peut plonger vers le sol.',
    lower: 'On peut regarder tres bas, voire sous le perso.',
    higher: 'La vue plongeante est bridee.',
    useCase: 'Eviter que la camera passe sous le decor.',
    min: -1.2,
    max: 0.5,
    step: 0.01,
  }),
  f('camera', {
    id: 'camera.PITCH_MAX',
    group: 'aim',
    level: 'advanced',
    label: 'Angle haut maximal',
    unit: 'rad',
    readout: DEG,
    help: 'Jusqu ou la camera peut monter vers le ciel.',
    lower: 'On ne peut presque pas lever la tete.',
    higher: 'On regarde a la verticale, la camera peut se retourner.',
    useCase: 'Confort en montagne russe ou dans les sauts.',
    min: 0.2,
    max: 1.8,
    step: 0.01,
  }),

  // --- Inventaire ---------------------------------------------------------
  f('inventory', {
    id: 'inventory.MAX_CARRY_WEIGHT',
    group: 'carry',
    level: 'simple',
    label: 'Charge maximale portable',
    unit: 'kg',
    help: 'Poids que le perso peut transporter avant penalite.',
    lower: 'Il faut trier son sac en permanence.',
    higher: 'On emporte tout Beauvais dans ses poches.',
    useCase: 'Difficulte de la gestion d inventaire.',
    min: 1,
    max: 80,
    step: 0.5,
  }),

  // --- Ciel : formes peintes ----------------------------------------------
  f('sky', {
    id: 'sky.paint.enabled',
    group: 'paint',
    level: 'simple',
    label: 'Activer le ciel peint',
    help: 'Interrupteur du ciel procedural. 0 = ancien ciel seul, 1 = ciel peint actif.',
    lower: '0 : retour au ciel historique, utile pour comparer ou depanner.',
    higher: '1 : skydome peint actif.',
    useCase: 'Comparer avant / apres, ou desactiver en cas de souci de perf.',
    min: 0,
    max: 1,
    step: 1,
  }),
  f('sky', {
    id: 'sky.paint.opacity',
    group: 'paint',
    level: 'simple',
    label: 'Intensite des masses peintes',
    help: 'Presence globale des formes peintes dans le ciel.',
    lower: 'Ciel presque uni, tres sobre.',
    higher: 'Ciel tres charge, facon toile peinte.',
    useCase: 'Le curseur principal du style du ciel.',
    min: 0,
    max: 1.4,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.primaryShapeScale',
    group: 'paint',
    level: 'simple',
    label: 'Taille des grandes formes',
    help: 'Echelle des grandes masses organiques du ciel.',
    lower: 'Beaucoup de petites formes, ciel agite.',
    higher: 'Quelques grandes masses calmes.',
    useCase: 'Donner un ciel epique ou un ciel tranquille.',
    min: 0.35,
    max: 2.5,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.secondaryShapeScale',
    group: 'paint',
    level: 'advanced',
    label: 'Taille des details',
    help: 'Echelle de la couche secondaire qui casse les bords.',
    lower: 'Bords tres decoupes.',
    higher: 'Bords larges et doux.',
    useCase: 'Reglage fin de la texture du ciel.',
    min: 0.35,
    max: 2.5,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.warpStrength',
    group: 'paint',
    level: 'advanced',
    label: 'Deformation des formes',
    help: 'Force de deformation qui rend les masses moins geometriques.',
    lower: 'Formes rondes et regulieres.',
    higher: 'Formes tordues, effet peinture a l huile.',
    useCase: 'Casser la regularite du bruit.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.shapeSoftness',
    group: 'paint',
    level: 'advanced',
    label: 'Douceur des contours',
    help: 'Nettete de la transition entre ciel et peinture.',
    lower: 'Contours francs, style BD.',
    higher: 'Transitions diffuses, style aquarelle.',
    useCase: 'Accorder le ciel au rendu cell-shading.',
    min: 0.2,
    max: 2.2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.horizontalStretch',
    group: 'paint',
    level: 'advanced',
    label: 'Etirement vers l horizon',
    help: 'Allongement des masses en approchant de l horizon.',
    lower: 'Formes compactes.',
    higher: 'Longues bandes horizontales.',
    useCase: 'Donner de la perspective au ciel.',
    min: 0.5,
    max: 2.2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.animationSpeed',
    group: 'paint',
    level: 'simple',
    label: 'Vitesse d evolution du ciel',
    help: 'Vitesse a laquelle les masses se deforment avec le temps.',
    lower: 'Ciel fige, tres graphique.',
    higher: 'Ciel qui bouge visiblement, parfois distrayant.',
    useCase: 'Rendre le ciel vivant sans attirer l oeil.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.horizonIntensity',
    group: 'paint',
    level: 'advanced',
    label: 'Intensite des couleurs a l horizon',
    help: 'Force des couleurs pres de l horizon.',
    lower: 'Horizon delave.',
    higher: 'Horizon sature, couchers de soleil marques.',
    useCase: 'Renforcer les heures dorees.',
    min: 0.25,
    max: 1.8,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.zenithIntensity',
    group: 'paint',
    level: 'advanced',
    label: 'Intensite des couleurs au zenith',
    help: 'Force des couleurs au-dessus de la tete.',
    lower: 'Haut du ciel pale.',
    higher: 'Bleu profond marque.',
    useCase: 'Equilibrer haut et bas du ciel.',
    min: 0.25,
    max: 1.8,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.sunHaloIntensity',
    group: 'paint',
    level: 'simple',
    label: 'Halo du soleil',
    help: 'Intensite du halo stylise autour du soleil.',
    lower: 'Soleil discret.',
    higher: 'Gros halo eblouissant.',
    useCase: 'Dramatiser les levers et couchers.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.moonHaloIntensity',
    group: 'paint',
    level: 'simple',
    label: 'Halo de la lune',
    help: 'Intensite du halo stylise autour de la lune.',
    lower: 'Lune plate.',
    higher: 'Lune enveloppee de brume lumineuse.',
    useCase: 'Ambiance des scenes de nuit.',
    min: 0,
    max: 2,
    step: 0.01,
  }),

  // --- Ciel : lumiere et ambiance -----------------------------------------
  f('sky', {
    id: 'sky.paint.materialTint',
    group: 'light',
    level: 'simple',
    label: 'Teinte des lumieres',
    help: 'Force avec laquelle la couleur du ciel teinte les lumieres de la scene.',
    lower: 'Lumieres neutres, decor moins integre au ciel.',
    higher: 'Toute la ville prend la couleur de l heure.',
    useCase: 'Lier l ambiance du sol a celle du ciel.',
    warning: 'Agit aussi sur la lisibilite du decor la nuit.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.fogIntensity',
    group: 'light',
    level: 'simple',
    label: 'Densite du brouillard',
    help: 'Epaisseur du fog colore selon l heure.',
    lower: 'Vue degagee, on voit loin.',
    higher: 'Ville noyee dans la brume, meilleure perf mais moins de profondeur visible.',
    useCase: 'Cacher le bord du monde ou creer une ambiance.',
    min: 0.2,
    max: 2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.cloudTint',
    group: 'light',
    level: 'advanced',
    label: 'Teinte des nuages',
    help: 'Integration colorimetrique des nuages au ciel.',
    lower: 'Nuages blancs detaches du ciel.',
    higher: 'Nuages fondus dans la couleur du ciel.',
    useCase: 'Eviter des nuages qui « collent » mal au ciel peint.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.particleIntensity',
    group: 'light',
    level: 'advanced',
    label: 'Poussieres dans l air',
    help: 'Densite des particules atmospheriques rares.',
    lower: 'Air parfaitement propre.',
    higher: 'Poussieres visibles dans les rais de lumiere.',
    useCase: 'Ajouter de la matiere aux heures dorees.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
  f('sky', {
    id: 'sky.paint.horizonGlowIntensity',
    group: 'light',
    level: 'advanced',
    label: 'Halo bas de l horizon',
    help: 'Force du halo horizontal quand le soleil est bas.',
    lower: 'Horizon net.',
    higher: 'Bande lumineuse marquee au ras du sol.',
    useCase: 'Renforcer l heure doree.',
    min: 0,
    max: 2,
    step: 0.01,
  }),
]

function f(section: DevSectionId, entry: Omit<DevTuningField, 'section' | 'kind'>): DevTuningField {
  return { ...entry, section, kind: 'number' }
}
